version: "3"
services:
  rakomqtt_commander:
    image: rakomqtt
    container_name: rakomqtt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - "./start.sh"
      - "--mqtt-host"
      - "127.0.0.1"
      - "--mqtt-user"
      - "${MOSQUITTO_HASS_USER}"
      - "--mqtt-password"
      - "${MOSQUITTO_HASS_PASSWORD}"
      - "--debug"
    network_mode: "host"
